- include_vars: vars_user.yml
- include_vars: sshkey.yml

# create group lesbain for ansible
- name: users | ansible | create group
  tags: group
  group:
    name: "{{ansible_user}}"
    state: present

# create user lesbian and add group
- name: users | ansible | create user
  tags: user
  user:
    name: "{{ansible_user}}"
    group: "{{ansible_user}}"
    groups: "{{ansible_user}} , root"
    state: present
    comment: "ansible User"

# add user lesbian to sudoers file
- name: users | ansible | add sudoers file
  tags: sudoer sudoers
  become: true
  copy:
    src: sudoers_lesbian
    dest: /etc/sudoers.d/lesbian
    owner: root
    group: root
    mode: 0440

# create .ssh directory for user lesbian
- name: users | ansible | create .ssh directory
  tags: ssh
  file:
    path: /home/lesbian/.ssh
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0700
  
# add sshkey for user lesbian
- name: add ssh key for User ansible
  tags: ssh sshkey
  become_user: "{{ansible_user}}"
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: "{{leasbianssh}}"