---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: yes
      changed_when: False

- hosts: localhost
  connection: local  
  become: true
  roles:
    - package
    - terminal
    - bash
    - tmux
    - lesbian
    - unattended
    - unattended_upgrade
    - wallpaper
    - clock
    - locale
    - microcode
    - upgrade
    - discord
    - favorite
    # - vscode
    - snap_install
    
    
    ##- include: tasks/cron.yml
    ### Monero ###
    #- include: tasks/xmrig.yml
    #- include: tasks/cron_monero.yml
    