- name: Download Discord
  tags: Discord
  become_user: freaky
  get_url: 
    url=https://discord.com/api/download?platform=linux&format=deb
    dest=/home/freaky/Downloads/discord.deb
 
- name: Install Discord 
  tags: Discord
  become: true
  apt: 
    deb=/home/freaky/Downloads/discord.deb