- include_vars: vars_package.yml

- name: Install packages
  tags: package
  become: true
  package:
    name:
      - "{{ openssh_server_package }}"
      - "{{ openssh_service }}"
      - "{{ monitor_system }}"
      - "{{ mutli_terminal }}"
      - "{{ curl_package }}"
      - "{{ wget_package }}"
      - "{{ python_package }}"
      - "{{ python_psutil_package }}"
      - "{{ network_tools }}"
      - "{{ dconf_package }}"
      - zsh
      - " {{ rsync_package }}"
      - sshfs
      - traceroute
      - whois
      - nmap
      - colordiff
      - at    
      - "{{ dns_utils_package }}"
      - screen
    state: latest
