---
- name: Host name list...
  hosts: localhost
  connection: local
  become: true
  vars:
    wall: "{{ choice | random }}"  
    choice:
    - "Wallpaper/Angela Gossow 2.jpg"
    - "Wallpaper/Angela Gossow.jpg"
    - "Wallpaper/Arch.jpg"
    - "Wallpaper/Arch logo.jpg"

  tasks:
  - name: copy from vars 1
    copy:
      src: "{{ wall }}"
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: freaky
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: freaky
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
