- include_vars: vars_user.yml

# set backgroud color for terminal
- name: set terminal color
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(0,0,0)'"

# set text color for terminal
- name: set terminal color foreground
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(211,215,207)'"

# set transparency for terminal
- name: set terminal transparency
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "15"

# remove default Theme transparency 
- name: set terminal transparency theme to False
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-transparency"
    value: "false"

# set backgroud transparency to ture
- name: set terminal transparency to "true"
  become_user: "{{main_user}}"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparency-backgroud"
    value: "true"