- name: Download Visual Stuido
  tags: vscode
  become_user: freaky
  get_url: 
    url=https://go.microsoft.com/fwlink/?LinkID=760868
    dest=/home/freaky/Downloads/vscode.deb
 
- name: Install Visual Stuido 
  tags: vscode
  become: true
  apt: 
    deb=/home/freaky/Downloads/vscode.deb