- include_vars: vars_openssh.yml

# install openssh server on machine
- name: open ssh | install openssh or update
  tags: openssh,ssh,system,setting
  package:
    name: "{{openssh_server_package}}"
    state: latest
  notify: restart_sshd

# make sure openssh is started and enable
- name: open ssh | enable service
  tags: openssh,ssh,system,setting
  service: 
    name: "{{openssh_service}}"
    enabled: yes
    state: started

## copy ssh config files

- name: open ssh | generate sshd_config files from template
  tags: openssh,ssh,system,setting
  template:
    src: /sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify: restart_sshd

# set log-in message on ssh 
- name: openssh | issue.net | log-in message
  tags: openssh,ssh,system,setting
  copy:
    src: /openssh_issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644


