# remove unwanted packages for fresh intsall 
- include_vars: cleanup.yml 

- name: cleanup packages remove unneeded packages...
  tags: cleanup
  become: true
  apt:
    name:
      - "{{ cow }}"
      - "{{ vim }}"
      - "{{ exi }}"
      - "{{ exibase }}"
      - "{{ exiconfig }}"
    state: absent
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'