- include_vars: vars_sshkey.yml


- name: add ssh key for User ansible
  tags: ssh sshkey 
  become_user: lesbian
  authorized_key:
    user: lesbian
    state: present
    key: "{{ leasbianssh }}"
    ## change state to absent to remove key and present to add ##