# Do Distro Upgrade
- name: Do Distro Upgrade
  tags: upgrade
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

# remove dependencies
- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes