- include_vars: vars_package.yml

- name: Install packages
  tags: package
  become: true
  package:
    name:
      - "{{ monitor_system }}"
      - "{{ mutli_terminal }}"
      - "{{ curl_package }}"
      - "{{ wget_package }}"
      - "{{ python_package }}"
      - "{{ python_psutil_package }}"
      - "{{ network_tools }}"
      - "{{ dconf_package }}"
      - "{{ matrix }}"
      - "{{ rsync_package }}"
      - "{{ trace_package }}"
      - "{{ nmap }}"
      - "{{ cdiff }}"
      - "{{ dns_utils_package }}"
      - at
      - screen
      - sshfs
      - whois
      - zsh
    state: latest
