- include_vars: vars_package.yml

- name: Install packages
  tags: package
  become: true
  package:
    name:
      - "{{ monitor_system }}"
      - "{{ mutli_terminal }}"
      - "{{ curl_package }}"
      - "{{ wget_package }}"
      - "{{ python_package }}"
      - "{{ python_psutil_package }}"
      - "{{ network_tools }}"
      - "{{ dconf_package }}"
      - "{{ terminal_screen_saver }}"
      - "{{ rsync_package }}"
      - "{{ trace_package }}"
      - "{{ network_mapper }}"
      - "{{ cdiff }}"
      - "{{ dns_utils_package }}"
      - at
      - "{{ mutli_screen }}"
      - "{{ ssh_mount }}"
    state: latest
